wayne: Force non-ab update package
AssertionError: META/ab_partitions.txt is required for ab_update.

Change-Id: I8c80871dd144caa8964be3bd0b0a24fac1fca982
Signed-off-by: Joe7500 <j7545032@gmail.com>
Signed-off-by: Edwiin Kusuma Jaya <kutemeikito0905@gmail.com>